### PR TITLE
Improved the loading overlay.

### PR DESCRIPTION
**Pull request by radiantdinosaurs**
Set the loading overlay to show by default, and remove only when certain functions on the pages it's on complete. Also, moved the loading overlay to the correct container within `home.html`.

Issue #20

### CODE REVIEW

**Comment by davidgatti** [comment]
Cool, one more thing - you hide the div with custom CSS, it be best to use what Boostrap 4 has to offer, in this case the `d-none` class - https://getbootstrap.com/docs/4.0/migration/#utilities. If you think this is good, switch to it, if not let me know why not. I'm not a CSS expert so maybe I understand this utility class incorrectly.

**Comment by radiantdinosaurs** [comment]
Bootstrap's `d-none` class toggles the CSS property display to `none`. The reason why I decided to manipulate the CSS with jQuery vs. changing the HTML class is because of transition. By setting the opacity to 0, I'm able to ease out the loading overlay and then hide it. If I were changing the HTML class instead, it wouldn't be animated, because `display` cannot be animated.

Another option is to use jQuery's fadeOut() method, but this is only possible is we add in the full jQuery library instead the slim one.

I can always fade out the element, and then add in the HTML class. Or we can get rid of the transition all together. Thoughts?

**Comment by davidgatti** [comment]
I love the explanation :) distill it in to a comment, and add it to that line of code, so anyone in the future will know what is up.

**Comment by davidgatti** [comment]
[Screen Recording 2018-10-03 at 9.27.04 PM.mov.zip](https://github.com/0x4447/contract.0x4447.com/files/2443503/Screen.Recording.2018-10-03.at.9.27.04.PM.mov.zip)

One extra thing, some how, despite the Loading Div being first, and already displayed, for a split sec, you see what is behind it. Any ideas how to improve this be nice, but if no solution can be found for now we can skip this part.

**Comment by radiantdinosaurs** [comment]
Hmm, I see the problem in the video, but I'm not able to replicate it on my end. I ran the app in Firefox and Chrome and even throttled the network speed, but it doesn't flicker for me.

You're sure you were on the right branch, pulled, and had built the app before running? What browser/version were you running?

**Comment by davidgatti** [comment]
yep, last commit, interesting, this is not the end of the world so we can skip it for now, I'll keep an eye on this and check with other computers. Just add the commend, and we can merge this PR :)

**Comment by davidgatti** [comment]
@radiantdinosaurs check my commit, I changed the wording. I want more of a WHY we doing it, and WHY also we are not doing it. SO it is clear for anyone why we made that decision.

**Comment by radiantdinosaurs** [comment]
Got it, I'll keep that in mind for the future.

**Pull request merged**
